### ISSUE TITLE
tslint-staged wont run: /usr/bin/env: «node\r»: No suck file or directory

### ISSUE THREAD

**Issue by GorillaBus** [hugoMencoboni/tslint-staged#1]
Hi, when I try to run tslint-staged with husky or even from the command line (for example calling `./node_modules/.bin/tslint-staged`) I'm getting the following error:

```
[edu@localhost test-project]$ git commit
husky > pre-commit (node v12.15.0)
/usr/bin/env: «node\r»: No suck file or directory
```
I'm running Fedora Linux version 32 with: 
node v12.15.0 
yarn 1.22.0
npm 6.13.4

My project runs with yarn workspaces. Everything is configured correctly and I can run `tslint` alone with no issues.

Thanks in advance!

**Comment by hugoMencoboni** [comment]
Hello @GorillaBus and thanks for this feedback.

It seems to be a problem with [line ending when publishing from a Windows machine](http://foldingair.blogspot.com/2013/05/developing-node-modules-npm-and-git-how.html), I'll try to publish a new version as soon has possible !

**Comment by hugoMencoboni** [comment]
I just [publish a new package on npm!](https://www.npmjs.com/package/tslint-staged/v/0.1.3)

@GorillaBus could you let me know if everything works with this new version?

Thanks!
